export const SEED_PHRASES: { japanese: string; english: string; situation?: string }[] = [
  { japanese: "iphoneでコピーしやすい形式で表示してください。", english: "Please display it in a format that's easy to copy on an iPhone." },
  { japanese: "問題を見た瞬間に分からなかった。", english: "I didn't know the answer the second I looked at the problem." },
  { japanese: "日本での癖です。", english: "That's just a habit from Japan." },
  { japanese: "助手席でいいですか。", english: "Is it okay if I sit in the passenger seat?" },
  { japanese: "土日は駐車場が混んでいると聞きました。", english: "I heard the parking lot gets really crowded on weekends." },
  { japanese: "他に誰が来ますか？", english: "Who else is coming?" },
  { japanese: "思っていたより疲れていたようで", english: "I must have been more tired than I thought" },
  { japanese: "たくさん寝てしまいました。", english: "because I ended up sleeping a lot." },
  { japanese: "昨日まではそんなに疲れを感じませんでした。", english: "I didn't feel that tired until yesterday." },
  { japanese: "どこかに写っていると思うんだけど", english: "I'm pretty sure it's in here somewhere." },
  { japanese: "トイレが近いんです。", english: "I have a small bladder." },
  { japanese: "寝てましたね", english: "You were sleeping, weren't you?" },
  { japanese: "韓国では整形するのが普通と聞きました。", english: "I heard plastic surgery is pretty common in Korea." },
  { japanese: "ここではみんな時間にルーズだとわかりました。", english: "I realized people are pretty laid-back about time here." },
  { japanese: "誰かしら時間に間に合いません。", english: "Someone's always running late." },
  { japanese: "水筒がカバンの中でこぼれた。", english: "My water bottle leaked in my bag." },
  { japanese: "カバンが水浸した。", english: "My bag got soaked." },
  { japanese: "カバンが砂だらけだ。", english: "My bag is full of sand." },
  { japanese: "あなたの家の玄関の前にいます。", english: "I'm right outside your front door." },
  { japanese: "私の言ったこと伝わりましたか？", english: "Did what I said get across?" },
  { japanese: "汚い字でごめんなさい", english: "Sorry for my messy handwriting." },
  { japanese: "部屋が臭くて困っています。", english: "My room stinks and it's super annoying." },
  { japanese: "人の命を預かる仕事だ。", english: "We hold people's lives in our hands." },
  { japanese: "海に入ったんですか？", english: "Did you go in the ocean?" },
  { japanese: "船便で送りました。", english: "I sent it by sea mail." },
  { japanese: "皆さん、一緒に写真を撮って貰えませんか？", english: "Could you guys take a picture with me?" },
  { japanese: "トイレに寄っていました。", english: "I stopped by the bathroom." },
  { japanese: "何の車のマークですか？", english: "What car logo is that?" },
  { japanese: "席が空くのを待っているんですか？", english: "Are you waiting for a seat to open up?" },
  { japanese: "私のために無理してくれなくても大丈夫です。", english: "Don't push yourself for me" },
  { japanese: "日焼けがひどいです。", english: "I got a really bad sunburn." },
  { japanese: "ホームページには1時って書いてありましたよね？", english: "The website said 1 o'clock, right?" },
  { japanese: "トップしてしまいました。", english: "I thinned it. It was thin." },
  { japanese: "ダフッてしまいました。", english: "I chunked it. That was chunked." },
  { japanese: "日本の方が湿気ているが、LAも暑い", english: "Japan is more humid, but LA is hot too." },
  { japanese: "これは、そういうネタです。", english: "It's just an inside joke." },
  { japanese: "聞き間違えました。", english: "I misheard you." },
  { japanese: "面倒だ！", english: "What a pain!" },
  { japanese: "何問か間違えちゃった", english: "I messed up some questions." },
  { japanese: "間違えた！", english: "I made a mistake." },
  { japanese: "荷物を預けにきた。", english: "I came by to drop off the luggage." },
  { japanese: "お願いがあります。", english: "I have a favor to ask. Could you do me a favor?" },
  { japanese: "ビーガン料理はいつもこれぐらい薄味なんですか？", english: "Are vegan dishes usually this mild?" },
  { japanese: "野菜はドレッシングがないと味がなさすぎる", english: "Vegetables are way too bland without dressing" },
  { japanese: "意外と、スコアは80後半が多いです。", english: "Surprisingly, my scores are often in the high 80s." },
  { japanese: "同じリュックがいっぱいなので、混ざってしまう。", english: "a lot of the same backpacks, so they easily get mixed up." },
  { japanese: "セクションCの人とはよく会うので", english: "I run into people from Section C pretty often" },
  { japanese: "スイングはすぐに元に戻ってしまう。", english: "My swing always reverts back to the old one." },
  { japanese: "全部のクラブが左に飛びます。", english: "I'm pulling all my clubs to the left." },
  { japanese: "震度はその場所での揺れの程度を表す。", english: "Seismic intensity shows how strong the shaking is in a specific spot." },
  { japanese: "今度はもっとアニメの話をしましょう。", english: "Let's talk more about anime next time!" },
  { japanese: "それは偶然じゃなかった", english: "That was no coincidence." },
  { japanese: "記憶をなくしました。", english: "I blacked out." },
  { japanese: "酔っぱらってきました。", english: "I'm starting to get tipsy." },
  { japanese: "腕を組んで綱渡りをした。", english: "We walked the tightrope arm in arm." },
  { japanese: "久しぶりに走った。", english: "I haven't run in a while." },
  { japanese: "倒れそう", english: "I feel like I'm gonna pass out." },
  { japanese: "吐きそう。", english: "I feel like I'm gonna throw up." },
  { japanese: "マジ？", english: "No way!" },
  { japanese: "なるほど", english: "That makes sense." },
  { japanese: "一理あるね", english: "Fair enough." },
  { japanese: "なんて言えばいいかな…", english: "How should I put it…" },
  { japanese: "調子どう？", english: "How's it going?" },
  { japanese: "いい感じ、そっちは？", english: "Pretty good, how are you?" },
  { japanese: "本当にそれ！", english: "I know, right?" },
  { japanese: "どっちでもいいよ", english: "It's up to you." },
  { japanese: "それについて、あとで連絡するね", english: "I'll get back to you on that." },
  { japanese: "公共交通機関だと時間通りに着けません。", english: "Taking public transit won't get me there on time" },
  { japanese: "しっかり酔ってきた。", english: "I'm getting drunk." },
  { japanese: "寂しくて1日中泣いた", english: "I cried all day because I felt so lonely." },
  { japanese: "このタグの方が名前が見やすい。", english: "The name is more visible on this tag." },
  { japanese: "決勝ラウンドの最初の相手がブラジルでした。", english: "Our first opponent in the final round was Brazil." },
  { japanese: "マグニチュードは地震を実際に起きたところのエネルギーです。", english: "Magnitude shows the energy right where the earthquake happened." },
  { japanese: "偶然にも、話す人はほとんどCセクションの人だ。", english: "Coincidentally, almost everyone I talked to was from Section C." },
  { japanese: "誰かクリアーしましたか？", english: "Did anyone clear/pass it?" },
  { japanese: "ノルウェーがブラジルを上回っていた。", english: "Norway was ahead of Brazil on merit." },
  { japanese: "ギリギリで合格だった。", english: "I barely passed." },
  { japanese: "お酒はよく飲むんですか？", english: "Do you drink much?" },
  { japanese: "可愛いもの好きです。", english: "I love cute stuff." },
  { japanese: "スライスに悩んでいます。", english: "I'm struggling with my slice." },
  { japanese: "強くはないが、お酒は好きです。", english: "I'm not a heavy drinker, but I do enjoy it." },
  { japanese: "今度飲みましょう！", english: "Let's grab a drink sometime!" },
  { japanese: "自信がありすぎて、横柄だ。", english: "He's way too confident and pretty arrogant." },
  { japanese: "子供のためのビジネスが上手くいけばいいと思うようになりました。", english: "I started hoping that a business for kids would succeed." },
  { japanese: "プロジェクトを掛け持ちしたことがあるが、どちらかがおろそかになってしまう。", english: "I've juggled multiple projects before, but one always ends up getting neglected." },
  { japanese: "直接会って話さないと関係がこじれる。", english: "If you don't talk in person, things get complicated." },
  { japanese: "テキストが最も感情が伝わらない", english: "Texting is the worst at getting feelings across." },
  { japanese: "会話がヒートアップしてしまう。", english: "The conversation gets pretty heated." },
  { japanese: "みんなが彼女のことをよく言っている。", english: "Everyone speaks highly of her." },
  { japanese: "こんな人にはなかなか出会えない。", english: "You don't meet people like this very often." },
  { japanese: "チームメンバー全員に才能がある。", english: "Everyone on the team is super talented." },
  { japanese: "くだらない授業だったわ", english: "That class was useless." },
  { japanese: "夏のインターンは挑戦したいと思っている", english: "I want to try a summer internship." },
  { japanese: "参考になります。", english: "That's helpful. I'll keep that in mind." },
  { japanese: "寝坊しました。", english: "Sorry, I slept in." },
  { japanese: "私たちは低く評価されている", english: "We are valued low." },
  { japanese: "味がいい", english: "The taste is amazing." },
  { japanese: "汗がひどい", english: "My sweat is crazy." },
  { japanese: "最近パターの調子が悪い", english: "My putting has been terrible lately." },
  { japanese: "最近ドジャースが調子悪い", english: "The Dodgers are awful right now." },
  { japanese: "日にちを間違えていました。", english: "I was wrong about the date" },
  { japanese: "予習した？", english: "Did you study in advance?" },
  { japanese: "なぜこの式が成り立つのか分からない", english: "I don't understand why this formula can be established" },
  { japanese: "公式を丸暗記しても仕方ないので、公式の導き方を覚えるようにしている。", english: "Just memorizing formulas is pointless, so I try to learn how to derive them." },
  { japanese: "自分で納得しないと、頭に入らない。", english: "If it doesn't make sense, I can't remember it" },
  { japanese: "4時間睡眠でも大丈夫です。", english: "Four hours of sleep is fine for me." },
  { japanese: "勘違いして、別の部屋に行きました。", english: "I got confused and went to the wrong room." },
  { japanese: "思ったより地震のニュースで騒いでいない。", english: "People aren't making that big of a deal about the earthquake news than I thought." },
  { japanese: "騙された！", english: "I got fooled!" },
  { japanese: "腕が痛い", english: "My arm hurts" },
  { japanese: "病気なら仕方ないね", english: "If you're sick, it can't be helped." },
  { japanese: "大事な時にいつもアップロードが始まる", english: "An upload always starts at the worst time." },
  { japanese: "せっかく無料なんだから使わない手はない", english: "It's free, so there's no reason not to use it." },
  { japanese: "読んで来いって簡単に言うけど、めっちゃ時間かかるんやぞ！", english: "It's easy to just say 'read it,' but it takes forever!" },
  { japanese: "金曜飲み過ぎたので今日はやめときます。", english: "I drank too much on Friday, so I'll pass today." },
  { japanese: "いつも課題を直前までやっています。ギリギリの提出です。", english: "I always work on my assignments until the last minute. I barely meet the deadline." },
  { japanese: "共通の趣味ができて、父親は喜んだ。", english: "My dad got really excited when we found a common interest." },
  { japanese: "みんなと一緒に過ごせて本当に嬉しいです。", english: "I'm so happy to be here with you all." },
  { japanese: "特別な日にしてくれてありがとう。", english: "Thanks for making my day special." },
  { japanese: "今までで最高の日です！", english: "This is the best day in LA ever!" },
  { japanese: "みんなで集合写真を撮ろう！", english: "Let's take a group photo!" },
  { japanese: "なんて優しいの！", english: "How sweet of you!" },
  { japanese: "みんなみたいな友達がいて本当に幸せです。", english: "I feel so lucky to have friends like you." },
  { japanese: "企画してくれてありがとう！", english: "Thanks for setting this up!" },
  { japanese: "泣かせないでよ～！", english: "Don't make me cry!" },
  { japanese: "これ以上の友達はいないよ。", english: "I couldn't ask for better friends." },
  { japanese: "おかわりいる？", english: "Can I get you a refill?" },
  { japanese: "生活には慣れてきた？", english: "Are you settling in okay?" },
  { japanese: "雰囲気最高！", english: "total vibes!" },
  { japanese: "どこか連れて行ってくれるの？", english: "Are you taking me somewhere?" },
  { japanese: "玄関に靴を置いてね", english: "Please leave your shoes in the entryway" },
  { japanese: "借りができましたね。今度返します。", english: "I owe you one. I'll pay you back next time." },
  { japanese: "空が広く見えます。", english: "The sky looks so open." },
  { japanese: "期待されても困るので、謙虚にいきます。", english: "I don't want too much pressure, so I'll stay humble." },
  { japanese: "部屋が汚くていつも妻に叱られます。", english: "My room is a mess, so my wife is always scolding me." },
  { japanese: "女性がよく発言する", english: "Women are more vocal here" },
  { japanese: "頼まれたことは頑張ってやります。", english: "Whatever I'm asked to do, I'll give it my all." },
  { japanese: "色々な領域に手を出し過ぎると、それぞれが浅くなる。", english: "Spreading yourself too thin means you cannot go deep." },
  { japanese: "こないだの飲み会で失敗したので、お酒を控えている。", english: "I made a mistake at the party the other day, so I'm cutting back on alcohol now." },
  { japanese: "前回の講義の内容を踏まえてまとめてみました。", english: "I put together a summary based on the last lecture." },
  { japanese: "税金をうまく調整すれば、その年の税金が安くなる。", english: "If you adjust your taxes properly, you can lower your tax bill for that year." },
  { japanese: "私の話はもういいですよ！", english: "That's enough talking about me!" },
  { japanese: "人数制限を超えているのはどうなるんですか", english: "What happens if we go over the limit?" },
  { japanese: "無くしてしまいました。届いていたりしますか", english: "I lost it. Has anyone turned it in by any chance?" },
  { japanese: "連投すみません。", english: "Sorry for the double email" },
  // Untranslated phrases
  { japanese: "コップがない", english: "" },
  { japanese: "油断した", english: "" },
  { japanese: "どこか遊びに行きませんか", english: "" },
  { japanese: "ハードルが高いです。", english: "" },
  { japanese: "後ろに座ると前の生徒の声が聞こえない。", english: "" },
  { japanese: "参考にします。", english: "" },
  { japanese: "やるより言うが易し", english: "" },
  { japanese: "どれかのクラスで聞きました。", english: "" },
  { japanese: "長袖の方がいいわ", english: "" },
  { japanese: "先生に当てられないかドキドキしてた", english: "" },
  { japanese: "もう終わりか！", english: "" },
  { japanese: "迷惑かけないように気を付けます。", english: "" },
  { japanese: "困ったときは助けてください。", english: "" },
  { japanese: "宿題はそれだけですよね？", english: "" },
  { japanese: "めっちゃ汗かいた", english: "" },
  { japanese: "お酒強そうに見えます。", english: "" },
  { japanese: "なんであなたが", english: "" },
  { japanese: "パソコンの不調で作業がはかどらない", english: "" },
  { japanese: "その価値がありますか？", english: "" },
  { japanese: "どっちにしろ", english: "" },
  { japanese: "食べないと倒れるわ", english: "" },
  { japanese: "学食に連れていってもらえませんか", english: "" },
  { japanese: "情報が被っている", english: "" },
  { japanese: "一日中ぼーっと映画を見ていました。", english: "" },
  { japanese: "そこまで主張したいことでもない。", english: "" },
  { japanese: "建設作業員は気性が荒い", english: "" },
  { japanese: "なぜこの数字は150でないんですか？", english: "" },
  { japanese: "メモとるのが間に合わない", english: "" },
  { japanese: "ようやく生活が落ち着いてきました", english: "" },
  { japanese: "減価償却費は概念だから、実際にお金が出て行っているわけではない", english: "" },
  { japanese: "適当に書くと後で困りそう", english: "" },
  { japanese: "ついに授業に追いついた", english: "" },
  { japanese: "今日はいつもより調子が悪い", english: "" },
  { japanese: "なんで水曜進むんだ！", english: "" },
  { japanese: "その可能性が高いね", english: "" },
];
